create table Aluno(
	idAluno integer not null,
	Nome varchar(50),
	primary key(idAluno)
);

CREATE TABLE DISCIPLINA (
    IDDISCIPLINA INTEGER NOT NULL,
    DESCRICAO     VARCHAR(50),
    PRIMARY KEY (IDDISCIPLINA)
);


CREATE TABLE PROFESSOR (
    IDPROFESSOR INTEGER NOT NULL,
    NOME     VARCHAR(50),
    PRIMARY KEY (IDPROFESSOR)
);


CREATE TABLE PROFESSOR_DISCIPLINA (
    IDPROFESSOR INTEGER NOT NULL,
    IDDISCIPLINA INTEGER NOT NULL,
    PRIMARY KEY (IDPROFESSOR, IDDISCIPLINA)
);


CREATE TABLE ALUNO_DISCIPLINA (
    IDALUNO INTEGER NOT NULL,
    IDDISCIPLINA INTEGER NOT NULL,
    NOTAPRIPER NUMERIC(15,2) default 0,
    NOTASEGPER NUMERIC(15,2) default 0,
    NOTATERPER NUMERIC(15,2) default 0,
    NOTAQUAPER NUMERIC(15,2) default 0,
    NOTATRABPRIPER NUMERIC(15,2) default 0,
    NOTATRABSEGPER NUMERIC(15,2) default 0,
    NOTATRABTERPER NUMERIC(15,2) default 0,
    NOTATRABQUAPER NUMERIC(15,2) default 0,
    PRIMARY KEY (IDALUNO, IDDISCIPLINA)
);


